services:
  - type: web
    name: petshop-api
    runtime: node
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
